<?php
    include '../database/data.php';
?>

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
        <img class="p-2" src="../assets/img/logo.png" alt="Logo">
        <a class="navbar-brand text-white" href="/">Legado Histórico</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="/">Início</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="../pages/sobre.php">Sobre</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right me-4">
                <li>
                    <span class="text-white me-4"><?= $nomeCompleto ?></span>
                </li>
                <li>
                    <a class="text-white " href="../auth/sair.php">Sair</a>
                </li>
            </ul>
        </div>
    </div>
</nav>